sudo: required

services:
  - docker

install:
  - docker build -t dockertestimage .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run --privileged -e ci_env -ti -d --name testcontainer dockertestimage
  - docker exec testcontainer make travis-build
  - docker stop testcontainer
  - docker rm testcontainer

notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF
